model: dinov3_dense_features_with_linear_head
model_kw:
  backbone_cfg:
    name: dinov3_backbone
  freeze_backbone: false

# backbone_cfg:
#   name: dinov3_ssl_finetune
#   config_path: /home/pwilson/projects/aip-medilab/pwilson/dinov3/experiments/2025-08-17_17-00-53/config.yaml
#   checkpoint_path: /home/pwilson/projects/aip-medilab/pwilson/dinov3/experiments/2025-08-17_17-00-53/ckpt/101249

loss: mil_prop_bce_entropy_reg
outside_prostate_penalty: false
add_image_clf: false
image_clf_mode: cspca
treat_gg1_as_benign: false
optimizer: adamw
lr: 1.0e-05
encoder_lr: 1.0e-05
warmup_lr: 0.0001
cnn_lr: 1.0e-05
warmup_epochs: 0
wd: 0.0
epochs: 35
accumulate_grad_steps: 1
cutoff_epoch: null
run_test: false
test_every_epoch: false
run_val: true
seed: 30
tracked_metric: val/core_auc_high_involvement
save_checkpoint_wandb: false
torch_compile: true
use_amp: true
device: cuda
checkpoint_dir: null
model_checkpoint: null
debug: false
save_best_weights: false

wandb:
  name: dinov3_ssl_ft
  project: miccai2024_comparison

evaluator:
  log_images: true
  log_images_every: 10
  include_patient_metrics: false
  
data:
  cohort_selection_mode: splits_file
  dataset: optimum
  batch_size: 64
  num_workers: 8
  augmentations: "none"
  image_size: 256
  first_downsample_size: null
  mask_size: 16
  limit_train_data: null
  train_subsample_seed: 42
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  adapter_cfg:
    image_orientation: probe_bottom
  frames: first
  crop_to_prostate: false
  rf_as_bmode: false
  include_rf: false
  root_dir: "/home/pwilson/projects/aip-medilab/pwilson/dinov3/data/exactvu_data/OPTIMUM/processed/UA_annotated_needles"
  splits_file: ${data.root_dir}/splits.json

