

model: dinov3_unetr_custom
model_kw: 
  backbone_cfg: 
    name: dinov3_ssl_finetune
    config_path: '/home/pwilson/projects/aip-medilab/pwilson/dinov3/experiments/2025-08-17_17-00-53/config.yaml'
    checkpoint_path: '/home/pwilson/projects/aip-medilab/pwilson/dinov3/experiments/2025-08-17_17-00-53/ckpt/89999'
  freeze_backbone: false
  image_size: ${data.image_size}

# model: dinov3_unetr
# model_kw: 
#   freeze_backbone: true
# metamodel:
#   mask_output_key: pred_masks

# loss
loss: mil_prop_bce_entropy_reg
outside_prostate_penalty: false
add_image_clf: false
image_clf_mode: cspca
treat_gg1_as_benign: false

# optimizer
optimizer: adamw
lr: 1.0e-05
encoder_lr: 1.0e-05
warmup_lr: 0.0001
cnn_lr: 1.0e-05
warmup_epochs: 0
wd: 0.0
epochs: 35
accumulate_grad_steps: 1
cutoff_epoch: null

# training
run_test: false
test_every_epoch: false
run_val: true

seed: 30
tracked_metric: val/core_auc_high_involvement
save_checkpoint_wandb: false

# device
torch_compile: true
use_amp: true
device: cuda

# system
checkpoint_dir: ${getenv:CHECKPOINT}
model_checkpoint: null

# misc
debug: false
save_best_weights: false

wandb: 
  name: dinov3_ssl_ft
  project: miccai2024_comparison

evaluator: 
  log_images: true
  log_images_every: 10
  include_patient_metrics: false

data:
  cohort_selection_mode: splits_file
  dataset: optimum
  batch_size: 8
  num_workers: 8
  augmentations: translate
  image_size: 256
  first_downsample_size: null
  mask_size: 256
  limit_train_data: null
  train_subsample_seed: 42
  mean:
  - 0
  - 0
  - 0
  std:
  - 1
  - 1
  - 1
  flip_ud: false
  frames: first
  crop_to_prostate: false
  rf_as_bmode: false
  include_rf: false
  root_dir: "/home/pwilson/projects/aip-medilab/pwilson/dinov3/data/exactvu_data/OPTIMUM/processed/UA_annotated_needles"
  splits_file: ${data.root_dir}/splits.json

