model: prostnfound_adapter_medsam_legacy
model_kw: 
  prompts: []
  checkpoint: /project/6106383/pwilson/checkpoints/pnf_plus_final_weights.pth

# loss
loss: mil_prop_bce_entropy_reg
outside_prostate_penalty: false
add_image_clf: false
image_clf_mode: cspca
treat_gg1_as_benign: false

# optimizer
optimizer: adamw
lr: 1.0e-05
encoder_lr: 1.0e-05
warmup_lr: 0.0001
cnn_lr: 1.0e-05
warmup_epochs: 0
wd: 0.0
epochs: 35
accumulate_grad_steps: 1
cutoff_epoch: null

# training
run_test: false
test_every_epoch: false
run_val: true

seed: 30
tracked_metric: val/core_auc_high_involvement
save_checkpoint_wandb: false

# device
torch_compile: true
use_amp: true
device: cuda

# system
checkpoint_dir: ${getenv:CHECKPOINT}
model_checkpoint: null

# misc
debug: false
save_best_weights: false

wandb: 
  project: miccai2024_comparison

evaluator: 
  log_images: false
  log_images_every: 100
  include_patient_metrics: false

data:
  cohort_selection_mode: splits_file
  dataset: optimum
  batch_size: 8
  num_workers: 8
  augmentations: translate
  image_size: 256
  first_downsample_size: null
  mask_size: 64
  limit_train_data: null
  train_subsample_seed: 42
  mean:
  - 0
  - 0
  - 0
  std:
  - 1
  - 1
  - 1
  flip_ud: false
  frames: first
  crop_to_prostate: false
  rf_as_bmode: false
  include_rf: false
  root_dir: "/home/pwilson/projects/aip-medilab/pwilson/dinov3/data/exactvu_data/OPTIMUM/processed/UA_annotated_needles"
  splits_file: ${data.root_dir}/splits.json

