defaults: 
  - _self_

# === Model Settings (will be overridden by checkpoint) ===
model: prostnfound_rl_adapter_medsam_legacy
model_kw:
  prompts: [age, psa]
  use_class_decoder: true
  num_attention_points: 3
  policy_type: categorical
  policy_hidden_dim: 256
  use_clinical_in_policy: true
  freeze_prostnfound: false
  temperature: 1.0

# === Checkpoint & Output ===
checkpoint: ${oc.env:PNF_RL_CHECKPOINT,null}  # path to .pth file with weights
output_dir: "???"      # REQUIRED: directory to save outputs

# === Dataset Configuration ===
data:
  fold: 0
  n_folds: 5
  test_center: null
  exclude_benign_cores_from_positive_patients: true
  involvement_threshold_pct: null
  undersample_benign_ratio: null
  cohort_selection_mode: kfold
  dataset: default
  batch_size: 8
  num_workers: 8
  train_subsample_seed: 42
  augmentations: translate
  image_size: 256
  first_downsample_size: null
  mask_size: 64
  limit_train_data: null
  mean: [0, 0, 0]
  std: [1, 1, 1]
  flip_ud: false
  frames: first
  crop_to_prostate: false
  rf_as_bmode: false
  include_rf: false

split: val         # Which split to evaluate on (e.g., val, test)

# === Calibration ===
calibrate_bias: false
calibrate_temperature: false
calibration_mode: null  # Options: "bag", "pixel", null

# === Metrics ===
include_patient_metrics: false

# === Save Options ===
save_checkpoint: false
save_raw_heatmaps: false
save_rendered_heatmaps: true
save_visualizations: false
save_format: png # could be "pdf" for vector graphics

# === RL-specific ===
save_attention_coords: true  # Save attention point coordinates
visualize_attention: true     # Overlay attention points on heatmaps

# === Inference & Processing ===
postprocess: true  # Whether to post-process heatmaps
device: cuda        # Device to use (e.g., cuda, cpu)
use_amp: false      # Use automatic mixed precision
torch_compile: false  # Use torch.compile if supported

